version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: message-center-postgres
    command: ["postgres", "-p", "5434"]
    restart: unless-stopped
    environment:
      POSTGRES_USER: purchase
      POSTGRES_PASSWORD: purchase
      POSTGRES_DB: purchase_db
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
